"""add share_location to user

Revision ID: 97acaf20f8bf
Revises: b5c2f2d8eb12
Create Date: 2026-05-03 16:45:42.626907

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "97acaf20f8bf"
down_revision: Union[str, Sequence[str], None] = "b5c2f2d8eb12"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "users",
        sa.Column(
            "share_location", sa.Boolean(), nullable=False, server_default=sa.false()
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "share_location")
    # ### end Alembic commands ###
