export const PLACE_CATEGORIES = [
  { value: 'restaurant', label: 'Restaurantes' },
  { value: 'cafe', label: 'Cafés' },
  { value: 'bar', label: 'Bares' },
  { value: 'museum', label: 'Museos' },
  { value: 'park', label: 'Parques' },
  { value: 'tourist_attraction', label: 'Turismo' },
  { value: 'supermarket', label: 'Supermercados' },
  { value: 'pharmacy', label: 'Farmacias' },
  { value: 'atm', label: 'Cajeros' },
  { value: 'gas_station', label: 'Gasolineras' },
  { value: 'gym', label: 'Gimnasios' },
  { value: 'hospital', label: 'Hospitales' },
  { value: 'subway_station', label: 'Transporte' },
  { value: 'movie_theater', label: 'Cines' },
  { value: 'night_club', label: 'Clubs' },
  { value: 'stadium', label: 'Estadios' },
  { value: 'zoo', label: 'Zoológicos' },
  { value: 'library', label: 'Bibliotecas' },
  { value: 'beach', label: 'Playas' },
  { value: 'bowling_alley', label: 'Boleras' },
  { value: 'bakery', label: 'Panaderías' },
  { value: 'shopping_mall', label: 'Centros comerciales' },
  { value: 'book_store', label: 'Librerías' },
]
